spring:
  datasource:
    username: education
    password: welcome1
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8081
